void main() {
  try {
    var result = 10 ~/ 10;
    print(result);
  } catch (e) {
    print("error : $e");
  }
}
